### ISSUE TITLE
Build failure because of dependency from UISF

### ISSUE THREAD

**Issue by jdagilliland** [Euterpea/Euterpea#25]
When building, I get the following error:
```
Building Euterpea-1.0.0...
Preprocessing library Euterpea-1.0.0...
[19 of 46] Compiling Euterpea.IO.MUI.MidiWidgets ( Euterpea/IO/MUI/MidiWidgets.lhs, dist/build/Euterpea/IO/MUI/MidiWidgets.o )

Euterpea/IO/MUI/MidiWidgets.lhs:311:31:
    Not in scope: `unsafeAsyncIO'

Euterpea/IO/MUI/MidiWidgets.lhs:314:36:
    Not in scope: `unsafeAsyncIOOn'
```

It seems to be due to the recent addition of `asyncMidi` and `asyncMidiOn`, which require those functions. Those functions were only recently added to UISF, later than the last hackage release, so if one does not already have UISF installed from source, build breaks.

**Comment by jdagilliland** [comment]
I should note that [this version]
(https://github.com/Euterpea/Euterpea/tree/bcd430e19ada48f15cb7db6768ef5ab5d681c60f) works fine.

**Comment by dwincort** [comment]
Thanks for pointing this out.  Although both current github builds work well together and both current Hackage builds work well together, this is caused because the most recent Euterpea github did not work with the older UISF Hackage release.  I've hopefully fixed the problem and will make sure to keep an eye on this dependency direction in the future.
