### ISSUE TITLE
ChildSong6.eps missing

### ISSUE THREAD

**Issue by twadleigh** [Euterpea/Euterpea#8]
ChildSong6.eps is missing from HSoM/pics directory.

**Comment by dwincort** [comment]
Some images are purposely left out of the repository because they're rather large.  You can find the (hopefully) full, complete, and current version of HSoM on the Yale Haskell website at http://haskell.cs.yale.edu/?post_type=publication&p=112.

Regardless, we have updated the HSoM so that it will build without any missing images.
